# .github/workflows/terraform-test.yml
name: Terraform Tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
  env:
      AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION:    us-west-2
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "latest"
          terraform_wrapper: false

      - name: Terraform Init
        run: |
          # 1. Force the runner to forget all cached provider metadata
          rm -rf .terraform/
          rm -f .terraform.lock.hcl
          
          # 2. Tell the OS to ignore the expired key temporarily so it can download the new one
          # 3. Use -upgrade to pull the newest version (v5.100.1+) which has the fixed keys
          terraform init -upgrade -input=false
        working-directory: modules/services/webserver-cluster

      - name: Run Unit Tests
        # Executes the .tftest.hcl files to validate module logic
        run: terraform test
        working-directory: modules/services/webserver-cluster

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    # Only runs on direct pushes to main after unit tests pass
    if: github.event_name == 'push'
    needs: unit-tests

    env:
      AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION:    us-west-2

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"
          cache: true

      - name: Run Integration Tests
        # Runs the Terratest suite located in the test/ directory
        run: go test -v -timeout 30m ./...
        working-directory: test
